# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
          java-version: '8' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
        
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
      
      - name: Setup Git identity
        run: git config --global user.email "ci@example.com"
      
      - name: Setup Git name
        run: git config --global user.name "GitHub CI"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash sportpaper build
        
      - uses: actions/upload-artifact@v2
        with:
          name: sportpaper-1.8.8-R0.1-SNAPSHOT
          path: SportPaper-Server/target/sportpaper-1.8.8-R0.1-SNAPSHOT.jar
